export const projects = [
  {
    title: 'Blogging website',
    description: "Complete MERN stack project where different people can register,login and write blogs with edit profile,change password, reset password, delete account, edit blog and delete blog functionallity. ",
      image: '/images/1.png',
      tags: ['React js','Css','Mongo DB','Express','Node','Cloudinary','Redux','Postman'],
    source: 'https://github.com/abir-sharma/mern',
    visit: 'https://mern1233.herokuapp.com/',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"Complete full stack project where different people can register, login and shop different items with edit profile, change password, reset password, add to cart and check order status functionallity",
    image: '/images/2.png',
    tags: ['Html','Css','Django','MySql','AWS','Postman'],
    source: 'https://github.com/abir-sharma/shop',
    visit: 'https://shop98762.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Meme uploader',
    description: "A complete blockchain powered project where people can post memes and other people can view them as well as can donate ethereum to meme creators.",
      image: '/images/3.jpg',
      tags: ['Bootstrap','Solidity','Ethereum','Ipfs','Remix IDE'],
    source: 'https://github.com/abir-sharma/meme',
    visit: 'https://memeuploader12.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Shopping website',
    description: "A complete full stack project where people can shop without login and register while admin can create, edit and delete products in shop with payment through card functionallity.",
    image: '/images/4.jpg',
    tags: ['Next js','Html','Css','Mongo DB','Stripe','Cloudinary','Redux','Postman'],
    source: 'https://github.com/abir-sharma/Next-js',
    visit: 'https://tshirt2100.vercel.app/',
    id: 3,
  },
  {
    title: 'Coding Monk',
    description: "An android + Ios app where people can learn web development,app development etc courses.",
    image: '/images/4.jpg',
    tags: ['React native','Redux','Mockend'],
    source: 'https://github.com/abir-sharma/andriodApp',
    visit: 'https://expo.dev/@abirsharma/coding-monk',
    id: 4,
  },
  {
    title: 'Loan predictor',
    description: "Made a Machine learning model which can predict whether loan of a particular person will approve or not according to a dataset and a given input with an accuracy of over 95%.",
    image: '/images/4.jpg',
    tags: ['Pandas','Seaborn','Sckikit learn'],
    source: 'https://github.com/abir-sharma/loan-prediction',
    visit: 'https://github.com/abir-sharma/loan-prediction',
    id: 5,
  },
  {
    title: 'Drawing website',
    description: "Complete full stack project where people can register login and find artists for work and artists can also register themselves their to get work.",
    image: '/images/4.jpg',
    tags: ['Bootstrap','Django','MySql','AWS'],
    source: 'https://github.com/abir-sharma/Drawing-website',
    visit: 'https://drwaingwallah99.herokuapp.com/',
    id: 6,
  },
];

export const TimeLineData = [
  // { year: `23rd jan 2022`, text: 'Started my journey', },
  // { year: `july 2022`, text: 'learnt the required skills', },
  // { year: `August 2022`, text: 'Working as freelancer', },
  // { year: 2020, text: 'Shared my projects with the world', },
  // { year: 2021, text: 'Started my own platform', },
];