export const projects = [
  {
    title: 'Blogging website',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['React js','Css','Mongo DB','Express','Node','Cloudinary','Redux','Postman'],
    source: 'https://github.com/abir-sharma/mern',
    visit: 'https://mern1233.herokuapp.com/',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['Html','Css','Django','MySql','AWS','Postman'],
    source: 'https://github.com/abir-sharma/shop',
    visit: 'https://shop98762.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Meme uploader',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['Bootstrap','Solidity','Ethereum','Ipfs','Remix IDE'],
    source: 'https://github.com/abir-sharma/meme',
    visit: 'https://memeuploader12.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Shopping website',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['Next js','Html','Css','Mongo DB','Stripe','Cloudinary','Redux','Postman'],
    source: 'https://github.com/abir-sharma/Next-js',
    visit: 'https://tshirt2100.vercel.app/',
    id: 3,
  },
  {
    title: 'Coding Monk',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React native','Redux','Mockend'],
    source: 'https://github.com/abir-sharma/andriodApp',
    visit: 'https://expo.dev/@abirsharma/coding-monk',
    id: 4,
  },
  {
    title: 'Loan predictor',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['Pandas','Seaborn','Sckikit learn'],
    source: 'https://github.com/abir-sharma/loan-prediction',
    visit: 'https://github.com/abir-sharma/loan-prediction',
    id: 5,
  },
  {
    title: 'Drawing website',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['Html','Css','Django','MySql','AWS'],
    source: 'https://github.com/abir-sharma/Drawing-website',
    visit: 'https://drwaingwallah99.herokuapp.com/',
    id: 6,
  },
];

export const TimeLineData = [
  // { year: `23rd jan 2022`, text: 'Started my journey', },
  // { year: `july 2022`, text: 'learnt the required skills', },
  // { year: `August 2022`, text: 'Working as freelancer', },
  // { year: 2020, text: 'Shared my projects with the world', },
  // { year: 2021, text: 'Started my own platform', },
];